### ISSUE TITLE
How's Progress

### ISSUE THREAD

**Issue by mjallday** [salrashid123/envoy_ext_proc#1]
I've been following but noticed there hasn't been activity for a couple of months.

Do you have thoughts around where development is and is there any structured way of understanding remaining development required? 

I've been watching this closely and think it's great!

**Comment by salrashid123** [comment]
thanks!.  funny enough, i actually just look for updates passively by checking in on commits here

https://github.com/envoyproxy/envoy/commits/main/source/extensions/filters/http/ext_proc/ext_proc.cc


if i see some updates on it that are interesting, i recode the sample here to accomodate it.   I do not know what the short-term/long-term roadmap is for that interms of features/capabilites.  Probably best to ask over there 

probably best to ask forupdates/roadmap over on envoy.  If you see any new feature thats interesting, feel free to PR here or i'll take a shot at it

**Comment by mjallday** [comment]
oh, thanks. i thought this was the trunk, not a branch. i'll go follow up over there :)
